version: '2'
services:
  product-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=productDB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
  product:
    image: product-service
    depends_on:
      - product-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=product-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=productDB
      - DATABASE_PORT=3306